### ISSUE TITLE
`lua.addon_manager.open` not found. Running the latest version of vscode with the latest exstension

### ISSUE THREAD

**Issue by Frityet** [LuaLS/vscode-lua#79]
<img width="258" alt="Screenshot 2023-03-02 at 06 17 14" src="https://user-images.githubusercontent.com/25426233/222453756-0920f768-e0dc-46cd-848c-9be69763d31b.png">

`uname:`
```sh
Darwin 22.2.0 Darwin Kernel Version 22.2.0: Fri Nov 11 02:08:47 PST 2022; root:xnu-8792.61.2~4/RELEASE_X86_64 x86_64
```
`vscode:`
```yaml
Version: 1.76.0
Commit: 92da9481c0904c6adfe372c12da3b7748d74bdcb
Date: 2023-03-01T10:23:45.993Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Darwin x64 22.2.0
Sandboxed: Yes
```
